### PR TITLE
More preauth tweaks but its still not happy :(

### PR DESCRIPTION
**Pull request by Firstyear**
Preauth is still failing with no actionable errors from the mit krb logs, and I can't find any options to enable debugging. I did correct a mistake on my part where I didn't put the enc timestamp in an encrypted data field, but now wireshark is showing the AS-REQ as valid.

Left is an AS-REQ from mit krb and right is our AS-REQ. I had to fix up kdc_options BitString to correctly be 32bits, and the XDR writer still isn't working properly from what I can see in wireshark so this temporarily adds a manual xdr header.

I'm really quite stumped here about why MIT KRB isn't happy with this request. Is there some way to enable debug logging in the kdc side to like ... see why it's throwing an error? 

Screenshot 2024-06-29 at 12 24 03
Screenshot 2024-06-29 at 12 24 18

### CODE REVIEW

**Comment by Firstyear** [comment]
Currently this seems to be mostly implemented but is failing tests. I'm thinking the next step is a small localhost demo kdc where mit krb tries to kinit to *us*, that way we can see what they issue for their pre-auth.

Generally I'm *very* held back by the abysmal logging in mit kdc so if you have a debugging trick I really need to hear it :)

**Comment by scabrero** [comment]
> Generally I'm _very_ held back by the abysmal logging in mit kdc so if you have a debugging trick I really need to hear it :)

The code if full of `#if DEBUG` and I there are no `--with-debug` or `--enable-debug` config switches. It doesn't even build with `DEBUG` defined and needs patching.  I will prepare a custom build in OBS and tune the dockerfile to pull krb5 from there.

**Comment by Firstyear** [comment]
> > Generally I'm _very_ held back by the abysmal logging in mit kdc so if you have a debugging trick I really need to hear it :)
> 
> The code if full of `#if DEBUG` and I there are no `--with-debug` or `--enable-debug` config switches. It doesn't even build with `DEBUG` defined and needs patching. I will prepare a custom build in OBS and tune the dockerfile to pull krb5 from there.

Thanks, we should just be able to add that as an obs repo into the Dockerfile and go from there.

But as mentioned in the meantime I'm just making a kdc so I can do the otherside of the equation.

**Comment by Firstyear** [comment]
Okay, huge slew of changes here. I wrote the worlds worst KDC example and can correctly decode a preauth-enc-timestamp from MIT KRB, and it compares the same to what I'm emitting. So that means it's "something else" I'm doing wrong in my AS-REQ at this point I think. I think before I get much further we should merge this as it has a lot of good cleanups, but I plan to break up the proto.rs file into smaller parts and remodel a bit of how the encryption is done. I also need to compare an AS-REQ side by side to see what the differences are in what is being emitted to try to solve the problem.

**Comment by Firstyear** [comment]
@scabrero I finally fixed it. MIT KRB expects the TCP socket to work like UDP where you connect and disconnect for EVERY REQUEST which is just silly. Anyway, pre-auth works now. I think we review and merge this, and then I want to do a huge cleanup of this to get the KDC working so we can work towards keytabs and TGS next.

**Comment by scabrero** [comment]
wow, lot of progress. I remember dealing with the kdc_options truncation, I will try to fix it. And WRT the XDR writer, I agree, it is so simple that we can do it by hand. Same for the XDR reader.

**Pull request merged**
